name: Deploy Application

on:
  workflow_run:
    workflows: ["Build & Deploy Static Site on Release"]
    types:
      - completed

jobs:
  pull:
    name: Pull Changes
    runs-on: ubuntu-latest
    steps:
      - name: Pull Latest
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            whoami
            pwd
            echo "========= GitHub Action for Pulling Data"
            cd /www/wwwroot/hol.siaji.com
            sudo -u www git reset --hard
            sudo -u www git checkout build
            sudo -u www git pull origin build

      - name: Fetch Latest Tags
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            whoami
            pwd
            echo "========= GitHub Action for Fetching Latest Tags"
            cd /www/wwwroot/build.siaji.com
            sudo -u www git fetch --tags